name: Support Request
description: Ask a question about this project
title: "[QUESTION]: "
labels: [support]
assignees:
  - iamnewton
  - brodrigu
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: give-me-this
    attributes:
      label: How can we help you?
      description: Ask anything you can think of, we're here to help.
    validations:
      required: true
  - type: textarea
    id: addtional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
