name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: >
          Hey @${{ github.event.issue.user.login }}!
          We really appreciate you taking the time to report an issue. The
          collaborators on this project attempt to help as many people as
          possible, but we are a limited number of volunteers, so it is
          possible that this will not be addressed as swiftly.
          Your patience is much appreciated and we will get back to you as
          quickly as possible.
        pr-message: >
          Hey @${{ github.event.issue.user.login }}!
          We really appreciate you taking the time to help out with this PR.
          The collaborators on this project attempt to help as many people as
          possible, but we are a limited number of volunteers, so it is
          possible that this will not be addressed as swiftly.
          Your patience is much appreciated and we will get back to you as
          quickly as possible.
