name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been automatically marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. Thank you for your contributions. If you think this is in error, please reopen the issue and comment with next steps or what you would like to see happen.'
        stale-pr-message: 'This PR has been automatically marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. Thank you for your contributions. If you think this is in error, please reopen the issue and comment with next steps or what you would like to see happen.'
        stale-issue-label: 'wontfix'
        stale-pr-label: 'wontfix'
