name: Test

on:
  push:
    branches:
      - '**'
      - '!main'
  pull_request:
    branches:
      - '**'
      - '!main'

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  test:
    needs: prepare
    name: Test on node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node:
          - 12
          - 13
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        env:
          CI: true
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test:unit
      - name: Integration
        run: npm run test:integration:ci
        env:
          JEST_PUPPETEER_CONFIG: jest-puppeteer.config.cjs
