name: Test

on:
  push:
    branches:
      - '**'
      - '!main'
  pull_request:
    types:
      - 'opened'
      - 'reopened'
    branches:
      - '**'
      - '!main'

jobs:
  docs:
    name: Inclusive language
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - name: Install dependencies
        env:
          CI: true
        run: npm ci
      - name: Alex
        run: npm run test:docs
  unit:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - name: Install dependencies
        env:
          CI: true
        run: npm ci
      - name: Unit Test
        run: npm run test:unit -- --ci --coverage
      - name: Send Coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/
          flags: unittests
          verbose: true

  e2e:
    name: End-to-End test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - name: Install dependencies
        env:
          CI: true
        run: npm ci
      - name: e2e Test
        run: npm run test:e2e
