name: Test

on:
  push:
    branches:
      - '**'
      - '!main'
  pull_request:
    branches:
      - '**'
      - '!main'

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  unit:
    needs: prepare
    name: Unit test on node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - name: Install dependencies
        env:
          CI: true
        run: npm ci
      - name: Unit Test
        run: npm run test:unit

  e2e:
    needs: prepare
    name: End-to-End test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node:
          - 14
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
      - name: Install dependencies
        env:
          CI: true
        run: npm ci
      - name: e2e Test
        run: npm run test:e2e
